CREATE TABLE `system_settings` (
	`id` text PRIMARY KEY NOT NULL,
	`pdf_watermark_enabled` integer DEFAULT false NOT NULL,
	`pdf_watermark_text` text DEFAULT 'CONFIDENCIAL',
	`pdf_watermark_opacity` text DEFAULT '0.10',
	`pdf_primary_color` text DEFAULT '#2563eb',
	`pdf_secondary_color` text DEFAULT '#64748b',
	`pdf_show_footer` integer DEFAULT true NOT NULL,
	`pdf_show_summary` integer DEFAULT true NOT NULL,
	`pdf_paper_size` text DEFAULT 'A4',
	`pdf_orientation` text DEFAULT 'portrait',
	`alert_mileage_threshold` integer DEFAULT 10000,
	`alert_license_days_before` integer DEFAULT 30,
	`alert_insurance_days_before` integer DEFAULT 30,
	`alert_maintenance_enabled` integer DEFAULT true NOT NULL,
	`alert_fines_enabled` integer DEFAULT true NOT NULL,
	`trips_require_approval` integer DEFAULT false NOT NULL,
	`trips_require_signature` integer DEFAULT false NOT NULL,
	`trips_max_speed` integer DEFAULT 0,
	`fuel_level_control` integer DEFAULT true NOT NULL,
	`fuel_min_level_alert` integer DEFAULT 20,
	`session_timeout_minutes` integer DEFAULT 0,
	`session_multi_login` integer DEFAULT true NOT NULL,
	`notifications_enabled` integer DEFAULT true NOT NULL,
	`audit_log_enabled` integer DEFAULT true NOT NULL,
	`audit_log_retention_days` integer DEFAULT 90,
	`created_at` text DEFAULT (datetime('now', 'localtime')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now', 'localtime')) NOT NULL
);
