CREATE TABLE `scheduled_trips` (
	`id` text PRIMARY KEY NOT NULL,
	`driver_id` text NOT NULL,
	`vehicle_id` text NOT NULL,
	`route_id` text,
	`scheduled_date` text NOT NULL,
	`origin` text,
	`destination` text,
	`purpose` text,
	`notes` text,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`trip_id` text,
	`launched_at` text,
	`cancelled_at` text,
	`cancelled_reason` text,
	`created_at` text DEFAULT (datetime('now', 'localtime')) NOT NULL,
	`created_by` text,
	`updated_at` text DEFAULT (datetime('now', 'localtime')) NOT NULL,
	`updated_by` text,
	`deleted_at` text,
	FOREIGN KEY (`driver_id`) REFERENCES `drivers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`route_id`) REFERENCES `routes`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`trip_id`) REFERENCES `trips`(`id`) ON UPDATE no action ON DELETE no action
);
