//src/types/types.d.ts
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on

// import { ICreateFuelStation, IFuelStation } from "./lib/types/fuel-station";
// import { IVehicle } from "./lib/types/vehicle";
// import { RestoreBackupReturn } from "./lib/types/backup";
// import { BackupReturn } from "./lib/types/backup";
// import { ValidatedLicense } from "./lib/types/licence";

// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
}

interface System {
    getSystemVersion: () => Promise<string>;
    getSchemaVersion: () => Promise<number>;
    forceDbRotation: () => Promise<void>
}

interface License {
    validateLicense: (license: string) => Promise<ValidatedLicense>;
    getMachineId: () => Promise<string>;
    checkExistingLicense: () => Promise<ValidatedLicense>;
    removeLicense: () => Promise<void>;
}

interface Backup {
    export: () => Promise<BackupReturn>;
    restore: () => Promise<RestoreBackupReturn>;
    getConfig: () => Promise<void>;
    updateConfig: () => Promise<void>;
    onProgress: (callback: (progress: any) => void) => void;
    onRestoreProgress: (callback: (progress: any) => void) => void;
    removeProgressListener: () => void;
    removeRestoreProgressListener: () => void;
}

interface Services {
    Auth: {
        login: (loginData: ILogin) => Promise<IUser>;
        logout: (userId: string) => Promise<string>;
        logoutAllUsers: () => Promise<void>;
        hasUsers: () => Promise<boolean>;
        createFirstUser: (userData: ICreateFirstUser) => Promise<IUser>;
        changePassword: (changePasswordData: IChangePassword) => Promise<any>;
        updateProfile: (userId: string, updateProfileData: IUpdateProfile) => Promise<IUser>;
    }
}

interface IClients {
    createClient: (clientData: any) => Promise<any>;
    getAllClients: () => Promise<any>;
    deleteClient: (clientId: string) => Promise<string>;
}


interface IVehicles {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<IVehicle>>;
    getById: (vehicleId: string) => Promise<IVehicle | null>;
    create: (vehicleData: ICreateVehicle) => Promise<IVehicle | null>;
    update: (vehicleId: string, vehicleData: IUpdateVehicle) => Promise<IVehicle | null>;
    delete: (vehicleId: string) => Promise<string | null>;
    getAvailable: () => Promise<IVehicle[]>;
    updateStatus: (vehicleId: string, data: IUpdateStatus) => Promise<IVehicle | null>;
    updateMileage: (vehicleId: string, mileage: number) => Promise<IVehicle | null>
}

interface IVehicleCategories {
    getAll: () => Promise<IVehicleCategory[]>;
    create: (data: ICreateVehicleCategory) => Promise<IVehicleCategory | null>;
    update: (id: string, data: IUpdateVehicleCategory) => Promise<IVehicleCategory | null>;
    delete: (id: string) => Promise<string | null>
}

interface IDrivers {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<IDriver>>;
    getById: (id: string) => Promise<IDriver | null>;
    create: (data: ICreateDriver) => Promise<IDriver | null>;
    update: (id: string, data: IUpdateDriver) => Promise<IDriver | null>;
    delete: (id: string) => Promise<string | null>;
    getActive: () => Promise<IDriver[]>;
    getAvailable: () => Promise<IDriver[]>;
    getExpiringLicenses: (days: number = 30) => Promise<IDriver[]>; 
}

interface ITrips {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<ITrip>>;
    getById: (id: string) => Promise<ITrip | null>;
    create: (data: ICreateTrip) => Promise<ITrip | null>;
    complete: (id: string, data: ICompleteTrip) => Promise<ITrip | null>;
    cancel: (id: string) => Promise<string | null>;
    getActive: () => Promise<ITrip[]>;
}
interface IRefuelingsWindow {
  getAll:       (params?: IRefuelingsPaginationParams)  => Promise<import('@/lib/types/pagination').IPaginatedResult<IRefueling>>;
  getById:      (id: string)                            => Promise<IRefueling | null>;
  getByVehicle: (vehicleId: string)                     => Promise<IRefueling[]>;
  getByDriver:  (driverId: string)                      => Promise<IRefueling[]>;
  getByTrip:    (tripId: string)                        => Promise<IRefueling[]>;
  getByStation: (stationId: string)                     => Promise<IRefueling[]>;
  getStats:     (params?: Pick<IRefuelingsPaginationParams, 'from_date' | 'to_date' | 'vehicle_id'>) => Promise<IRefuelingStats>;
  create:       (data: ICreateRefueling)                => Promise<IRefueling>;
  update:       (id: string, data: IUpdateRefueling)    => Promise<IRefueling | null>;
  remove:       (id: string)                            => Promise<boolean>;
}

interface IMaintenances {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<IMaintenance>>;
    create: (data: ICreateMaintenance) => Promise<IMaintenance | null>;
    update: (id: string, data: IUpdateMaintenance) => Promise<IMaintenance | null>;
    complete: (id: string, data: IUpdateMaintenance) => Promise<IMaintenance | null>;
    delete: (id: string) => Promise<string | null>;
    getCategories: () => Promise<IMaintenanceCategory[]>;
    getWorkshops: () => Promise<IWorkshop[]>;
    getActiveMaintenances: () => Promise<IMaintenance[]>;
    getMaintenanceById: (id: string) => Promise<IMaintenance | null>;
}

interface IMaintenanceCategories {
    getAll: () => Promise<IExpenseCategory>;
    create: (data: ICreateMaintenance) => Promise<IMaintenanceCategory>;
    getById: (id: string) => Promise<IMaintenanceCategory | null>;
    update: (id: string, data: IUpdateMaintenance) => Promise<IWorkshop>;
    delete: (id: string) => Promise<string>;
    getActive: () => Promise<IMaintenanceCategory[]>;
}

interface IExpenses {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<IExpense>>;
    getById: (id: string) => Promise<IExpense | null>;
    create: (data: ICreateExpense) => Promise<IExpense | null>;
    update: (id: string, data: IUpdateExpense) => Promise<IExpense | null>;
    markAsPaid: (id: string, data: PaymentData) => Promise<IExpense | null>;
    delete: (id: string) => Promise<string>;
    getByPeriod: (startDate: string, endDate: string) => Promise<IExpense[]>;
    getCategories: () => Promise<IExpenseCategory[]>;
}

interface IExpenseCategories {
    getAll: () => Promise<IExpenseCategory>;
    create: (data: ICreateExpense) => Promise<IExpenseCategory>;
    getById: (id: string) => Promise<IExpenseCategory | null>;
    update: (id: string, data: IUpdateExpense) => Promise<IWorkshop>;
    delete: (id: string) => Promise<string>;
    getActive: () => Promise<IExpenseCategory[]>;
}

interface IWorkshops {
    getAll: () => Promise<IWorkshop[]>;
    create: (data: ICreateWorkshop) => Promise<IWorkshop>;
    getById: (id: string) => Promise<IWorkshop | null>;
    update: (id: string, data: IUpdateWorkshop) => Promise<IWorkshop>;
    delete: (id: string) => Promise<string>;
}

interface IFuelStations {
    getAll: () => Promise<IFuelStation[]>;
    create: (data: ICreateFuelStation) => Promise<IFuelStation>;
    getById: (id: string) => Promise<IFuelStation | null>;
    update: (id: string, data: IUpdateFuelStation) => Promise<IFuelStation>;
    delete: (id: string) => Promise<IFuelStation>;
}

interface IRoutes {
    getAll: () => Promise<IRoute[]>;
    create: (data: ICreateRoute) => Promise<IRoute>;
    getById: (id: string) => Promise<IRoute | null>;
    getActive: () => Promise<IRoute[]>;
    update: (id: string, data: IUpdateRote) => Promise<IRoute>;
    delete: (id: string) => Promise<IRoute>;
}

interface IFines {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<IFine>>;
    getById: (id: string) => Promise<IFine | null>;
    create: (data: ICreateFine) => Promise<IFine | null>;
    update: (id: string, data: IUpdateFine) => Promise<IFine | null>;
    markAsPaid: (id: string, data: PaymentData) => Promise<IFine | null>;
    delete: (id: string) => Promise<string>;
    getPending: () => Promise<IFine[]>;
}

interface IDriverLeaves {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<IDriverLeave>>;
    getById: (id: string) => Promise<IDriverLeave | null>;
    getByDriver: (driverId: string) => Promise<IDriverLeave | null>;
    create: (data: ICreateDriverLeave) => Promise<IDriverLeave | null>;
    update: (id: string, data: IUpdateDriverLeave) => Promise<IDriverLeave | null>;
    runScheduler: () => Promise<void>;
    cancel: (id: string, data: IDriverLeave) => Promise<IDriverLeave | null>;
}

interface IDashboard {
    getStats: () => Promise<any>;
    getActivities: (limit: number) => Promise<any>;
    getChartData: () => Promise<any>;
}

interface IReports {
    getVehiclesData:   (dateRange: DateRange) => Promise<any>;
    getDriversData:    (dateRange: DateRange) => Promise<any>;
    getTripsData:      (dateRange: DateRange) => Promise<any>;
    getFuelData:       (dateRange: DateRange) => Promise<any>;
    getMaintenanceData:(dateRange: DateRange) => Promise<any>;
    getFinancialData:  (dateRange: DateRange) => Promise<any>;
    getGeneralData:    (dateRange: DateRange) => Promise<any>;
    listGenerated:     (filters?: { type?: string; startDate?: string; endDate?: string; search?: string }) => Promise<any[]>;
    getGenerated:      (id: string) => Promise<any>;
    deleteGenerated:   (id: string) => Promise<void>;
    statsGenerated:    () => Promise<{ total: number; thisMonth: number; byType: Record<string, number> }>;
    redownload:        (id: string) => Promise<any>;
    savePdf: (params: {
        base64:      string;
        fileName:    string;
        reportType:  string;
        title:       string;
        periodStart: string;
        periodEnd:   string;
        language:    string;
        data:        any;
        stats:       any;
    }) => Promise<{ success: boolean; path?: string; id?: string }>;
}

interface ICompany {
    get:           () => Promise<import('./lib/types/company').ICompanySettings | null>;
    isConfigured:  () => Promise<boolean>;
    update:        (data: import('./lib/types/company').IUpdateCompanySettings) => Promise<import('./lib/types/company').ICompanySettings>;
    uploadLogo:    (base64: string) => Promise<import('./lib/types/company').IUploadLogoResponse>;
    removeLogo:    () => Promise<import('./lib/types/company').ICompanySettings | null>;
    getLogoBase64: () => Promise<string | null>;
}

interface ISystemSettings {
  get:    () => Promise<import('./lib/types/system-settings').ISystemSettings>;
  update: (data: import('./lib/types/system-settings').IUpdateSystemSettings) => Promise<import('./lib/types/system-settings').ISystemSettings>;
  reset:  () => Promise<import('./lib/types/system-settings').ISystemSettings>;
}

interface IScheduledTrip {
    getAll:       (params?: any) => Promise<any>;
    getById:      (id: string)   => Promise<any>;
    getByDriver:  (driverId: string) => Promise<any[]>;
    create:       (data: any)    => Promise<any>;
    update:       (id: string, data: any) => Promise<any>;
    cancel:       (id: string, data?: any) => Promise<any>;
    runScheduler: () => Promise<void>;
  };

 export interface IDriverShifts {
  getAll: (params?: IDriverShiftsPaginationParams) => Promise<IPaginatedResult<IDriverShiftSummary>>;
  getById: (id: string) => Promise<IDriverShift | null>;
  getByDriver: (driverId: string) => Promise<IDriverShiftBadge[]>;
  getForDriver: (driverId: string) => Promise<IDriverShiftBadge[]>;
  getForAllDrivers: () => Promise<Record<string, IDriverShiftBadge[]>>;
  create: (data: ICreateDriverShift) => Promise<IDriverShift>;
  update: (id: string, data: IUpdateDriverShift) => Promise<IDriverShift | null>;
  updateStatus: (id: string, status: ShiftStatus) => Promise<IDriverShift | null>;
  remove: (id: string) => Promise<boolean>;
  addMember: (shiftId: string, data: IAddShiftMember) => Promise<IDriverShift | null>;
  removeMember: (shiftId: string, memberId: string) => Promise<IDriverShift | null>;
  setLeader: (shiftId: string, memberId: string) => Promise<IDriverShift | null>;
  updateMember: (shiftId: string, memberId: string, data: IUpdateShiftMember) => Promise<IDriverShift | null>;
  replaceMembers: (
    shiftId: string,
    members: { driver_id: string; is_leader: boolean; notes?: string }[]
  ) => Promise<IDriverShift | null>;
}

declare interface Window {
    system:                  System;
    license:                 License;
    backup:                  Backup;
    themeMode:               ThemeModeContext;
    electronWindow:          ElectronWindow;
    _service_auth:           Services["Auth"];
    _clients:                IClients;
    _vehicles:               IVehicles;
    _vehicle_categories:     IVehicleCategories;
    _drivers:                IDrivers;
    _trips:                  ITrips;
    _refuelings:             IRefuelings;
    _maintenances:           IMaintenances;
    _maintenance_categories: IMaintenanceCategories;
    _expenses:               IExpenses;
    _expense_categories:     IExpenseCategories;
    _workshops:              IWorkshops;
    _fuel_stations:          IFuelStations;
    _routes:                 IRoutes;
    _fines:                  IFines;
    _dashboard:              IDashboard;
    _reports:                IReports;
    _driverLeaves:           IDriverLeaves;
    _company:                ICompany;
    _system_settings: ISystemSettings;
    _scheduled_trips: IScheduledTrip;
    _driverShifts: IDriverShifts;
}