// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on

// import { RestoreBackupReturn } from "./lib/types/backup";
// import { BackupReturn } from "./lib/types/backup";
// import { ValidatedLicense } from "./lib/types/licence";

// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
}

interface System {
    getSystemVersion: () => Promise<string>;
    getSchemaVersion: () => Promise<number>;
}

interface License {
    validateLicense: (license: string) => Promise<ValidatedLicense>;
    getMachineId: () => Promise<string>;
    checkExistingLicense: () => Promise<ValidatedLicense>;
    removeLicense: () => Promise<void>;
}

interface Backup {
    export: () => Promise<BackupReturn>;
    restore: () => Promise<RestoreBackupReturn>;
    getConfig: () => Promise<void>;
    updateConfig: () => Promise<void>;
    onProgress: (callback: (progress: any) => void) => void;
    onRestoreProgress: (callback: (progress: any) => void) => void;
    removeProgressListener: () => void;
    removeRestoreProgressListener: () => void;
}

interface IClients {
    createClient: (clientData: any) => Promise<any>;
    getAllClients: () => Promise<any>;
    deleteClient: (clientId: string) => Promise<string>;
}

interface Services {
    Auth: {
        login: (loginData: ILogin) => Promise<IUser>;
        logout: (userId: string) => Promise<string>;
        hasUsers: () => Promise<boolean>;
        createFirstUser: (userData: ICreateFirstUser) => Promise<IUser>;
        changePassword: (changePasswordData: IChangePassword) => Promise<any>;
        updateProfile: (userId: string, updateProfileData: IUpdateProfile) => Promise<IUser>;
    }
}

declare interface Window {
    system: System;
    license: License;
    backup: Backup;
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    _clients: IClients;
    _service_auth: Services["Auth"];
}
