//src/types.d.ts
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on

// import { ICreateFuelStation, IFuelStation } from "./lib/types/fuel-station";
// import { IVehicle } from "./lib/types/vehicle";
// import { RestoreBackupReturn } from "./lib/types/backup";
// import { BackupReturn } from "./lib/types/backup";
// import { ValidatedLicense } from "./lib/types/licence";

// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
}

interface System {
    getSystemVersion: () => Promise<string>;
    getSchemaVersion: () => Promise<number>;
    forceDbRotation: () => Promise<void>
}

interface License {
    validateLicense: (license: string) => Promise<ValidatedLicense>;
    getMachineId: () => Promise<string>;
    checkExistingLicense: () => Promise<ValidatedLicense>;
    removeLicense: () => Promise<void>;
}

interface Backup {
    export: () => Promise<BackupReturn>;
    restore: () => Promise<RestoreBackupReturn>;
    getConfig: () => Promise<void>;
    updateConfig: () => Promise<void>;
    onProgress: (callback: (progress: any) => void) => void;
    onRestoreProgress: (callback: (progress: any) => void) => void;
    removeProgressListener: () => void;
    removeRestoreProgressListener: () => void;
}

interface Services {
    Auth: {
        login: (loginData: ILogin) => Promise<IUser>;
        logout: (userId: string) => Promise<string>;
        logoutAllUsers: () => Promise<void>;
        hasUsers: () => Promise<boolean>;
        createFirstUser: (userData: ICreateFirstUser) => Promise<IUser>;
        changePassword: (changePasswordData: IChangePassword) => Promise<any>;
        updateProfile: (userId: string, updateProfileData: IUpdateProfile) => Promise<IUser>;
    }
}

interface IClients {
    createClient: (clientData: any) => Promise<any>;
    getAllClients: () => Promise<any>;
    deleteClient: (clientId: string) => Promise<string>;
}


interface IVehicles {
    getAll: (params?: IPaginationParams) => Promise<IPaginatedResult<IVehicle>>;
    getById: (vehicleId: string) => Promise<IVehicle | null>;
    create: (vehicleData: ICreateVehicle) => Promise<IVehicle | null>;
    update: (vehicleId: string, vehicleData: IUpdateVehicle) => Promise<IVehicle | null>;
    delete: (vehicleId: string) => Promise<string | null>;
    getAvailable: () => Promise<IVehicle[]>;
    updateStatus: (vehicleId: string, status: string) => Promise<IVehicle | null>;
    updateMileage: (vehicleId: string, mileage: number) => Promise<IVehicle | null>
}

interface IVehicleCategories {
    getAll: () => Promise<IVehicleCategory[]>;
    create: (data: ICreateVehicleCategory) => Promise<IVehicleCategory | null>;
    update: (id: string, data: IUpdateVehicleCategory) => Promise<IVehicleCategory | null>;
    delete: (id: string) => Promise<string | null>
}

interface IDrivers {
    getAll: () => Promise<IDriver[]>;
    getById: (id: string) => Promise<IDriver | null>;
    create: (data: ICreateDriver) => Promise<IDriver | null>;
    update: (id: string, data: IUpdateDriver) => Promise<IDriver | null>;
    delete: (id: string) => Promise<string | null>;
    getActive: () => Promise<IDriver[]>;
    getAvailable: () => Promise<IDriver[]>;
    getExpiringLicenses: (days: number = 30) => Promise<IDriver[]>; 
}

interface ITrips {
    getAll: () => Promise<ITrip[]>;
    getById: (id: string) => Promise<ITrip | null>;
    create: (data: ICreateTrip) => Promise<ITrip | null>;
    complete: (id: string, data: ICompleteTrip) => Promise<ITrip | null>;
    cancel: (id: string) => Promise<string | null>;
    getActive: () => Promise<ITrip[]>;
}
interface IRefuelings {
    getAll: () => Promise<IRefueling[]>;
    create: (data: ICreateRefueling) => Promise<IRefueling | null>;
    getByVehicle: (id: string) => Promise<IRefueling[]>;
}

interface IMaintenances {
    getAll: () => Promise<IMaintenance[]>;
    create: (data: ICreateMaintenance) => Promise<IMaintenance | null>;
    update: (id: string, data: IUpdateMaintenance) => Promise<IMaintenance | null>;
    complete: (id: string, data: IUpdateMaintenance) => Promise<IMaintenance | null>;
    delete: (id: string) => Promise<string | null>;
    getCategories: () => Promise<IMaintenanceCategory[]>;
    getWorkshops: () => Promise<IWorkshop[]>;
    getActiveMaintenances: () => Promise<IMaintenance[]>;
    getMaintenanceById: (id: string) => Promise<IMaintenance | null>;
}

interface IMaintenanceCategories {
    getAll: () => Promise<IExpenseCategory>;
    create: (data: ICreateMaintenance) => Promise<IMaintenanceCategory>;
    getById: (id: string) => Promise<IMaintenanceCategory | null>;
    update: (id: string, data: IUpdateMaintenance) => Promise<IWorkshop>;
    delete: (id: string) => Promise<string>;
    getActive: () => Promise<IMaintenanceCategory[]>;
}

interface IExpenses {
    getAll: () => Promise<IExpense[]>;
    getById: (id: string) => Promise<IExpense | null>;
    create: (data: ICreateExpense) => Promise<IExpense | null>;
    update: (id: string, data: IUpdateExpense) => Promise<IExpense | null>;
    markAsPaid: (id: string, data: PaymentData) => Promise<IExpense | null>;
    delete: (id: string) => Promise<string>;
    getByPeriod: (startDate: string, endDate: string) => Promise<IExpense[]>;
    getCategories: () => Promise<IExpenseCategory[]>;
}

interface IExpenseCategories {
    getAll: () => Promise<IExpenseCategory>;
    create: (data: ICreateExpense) => Promise<IExpenseCategory>;
    getById: (id: string) => Promise<IExpenseCategory | null>;
    update: (id: string, data: IUpdateExpense) => Promise<IWorkshop>;
    delete: (id: string) => Promise<string>;
    getActive: () => Promise<IExpenseCategory[]>;
}

interface IWorkshops {
    getAll: () => Promise<IWorkshop[]>;
    create: (data: ICreateWorkshop) => Promise<IWorkshop>;
    getById: (id: string) => Promise<IWorkshop | null>;
    update: (id: string, data: IUpdateWorkshop) => Promise<IWorkshop>;
    delete: (id: string) => Promise<string>;
}

interface IFuelStations {
    getAll: () => Promise<IFuelStation[]>;
    create: (data: ICreateFuelStation) => Promise<IFuelStation>;
    getById: (id: string) => Promise<IFuelStation | null>;
    update: (id: string, data: IUpdateFuelStation) => Promise<IFuelStation>;
    delete: (id: string) => Promise<IFuelStation>;
}

interface IRoutes {
    getAll: () => Promise<IRoute[]>;
    create: (data: ICreateRoute) => Promise<IRoute>;
    getById: (id: string) => Promise<IRoute | null>;
    getActive: () => Promise<IRoute[]>;
    update: (id: string, data: IUpdateRote) => Promise<IRoute>;
    delete: (id: string) => Promise<IRoute>;
}

interface IFines {
    getAll: () => Promise<IFine[]>;
    getById: (id: string) => Promise<IFine | null>;
    create: (data: ICreateFine) => Promise<IFine | null>;
    update: (id: string, data: IUpdateFine) => Promise<IFine | null>;
    markAsPaid: (id: string, data: PaymentData) => Promise<IFine | null>;
    delete: (id: string) => Promise<string>;
    getPending: () => Promise<IFine[]>;
}

declare interface Window {
    system: System;
    license: License;
    backup: Backup;
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    _service_auth: Services["Auth"];
    _clients: IClients;
    _vehicles: IVehicles;
    _vehicle_categories: IVehicleCategories;
    _drivers: IDrivers;
    _trips: ITrips;
    _refuelings: IRefuelings;
    _maintenances: IMaintenances;
    _maintenance_categories: IMaintenanceCategories;
    _expenses: IExpenses;
    _expense_categories: IExpenseCategories;
    _workshops: IWorkshops;
    _fuel_stations: IFuelStations;
    _routes: IRoutes;
    _fines: IFines;
}
